openai.api.url=https://api.openai.com
quarkus.datasource.db-kind=postgresql

quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

openai.api.key=${OPENAI_API_KEY}

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.oidc.auth-server-url=${KEYCLOAK_URL}/realms/smart_linguo
quarkus.oidc.client-id=translation-api
quarkus.oidc.credentials.secret=${OIDC_SECRET}
quarkus.oidc.application-type=service
quarkus.oidc.tls.verification=none
keycloak.admin.url=${KEYCLOAK_URL}
keycloak.admin.master-realm=master
keycloak.admin.user-realm=smart_linguo
keycloak.admin.client-id=admin-cli
keycloak.admin.username=${KEYCLOAK_ADMIN_USER}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}
stripe.secret-key=${STRIPE_SK}
stripe.webhook-secret=${STRIPE_WHSEC}

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true