openai.api.url=https://api.openai.com
quarkus.datasource.db-kind=postgresql

quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

openai.api.key=${OPENAI_API_KEY}

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

quarkus.oidc.auth-server-url=http://localhost:8180/realms/smart_linguo
quarkus.oidc.client-id=translation-api
quarkus.oidc.credentials.secret=${OIDC_SECRET}
quarkus.oidc.application-type=service
quarkus.oidc.tls.verification=none

keycloak.admin.url=http://localhost:8180
keycloak.admin.master-realm=master
keycloak.admin.user-realm=smart_linguo
keycloak.admin.client-id=admin-cli
keycloak.admin.username=${KEYCLOAK_ADMIN_USER}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}

stripe.secret-key=${STRIPE_SK}
stripe.webhook-secret=${STRIPE_WHSEC}